netliva_symfony_form_dependent:
  path:     /netliva/form/dependent/{entity_alias}
  defaults: { _controller: Netliva\SymfonyFormBundle\Controller\DependentController::getOptionsAction }

netliva_symfony_form_autocomplate:
  path:     /netliva/form/autocomplate/{entity_alias}
  defaults: { _controller: Netliva\SymfonyFormBundle\Controller\AjaxAutocompleteController::getJSONAction }

netliva_symfony_form_autocomplate_back:
  path:     /netliva/form/autocomplate_back/{entity_alias}/{id}
  defaults: { _controller: Netliva\SymfonyFormBundle\Controller\AjaxAutocompleteController::callBackAction, id: null }

netliva_symfony_form_treeselect_getoption:
  path:     /netliva/form/treeselect/{entity_alias}/{val}
  defaults: { _controller: Netliva\SymfonyFormBundle\Controller\TreeSelectController::getOptionsAction }
