services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Netliva\SymfonyFormBundle\Services\FormErrorsService:
        class: Netliva\SymfonyFormBundle\Services\FormErrorsService
        public: false

    netliva.form_errors:
        alias: Netliva\SymfonyFormBundle\Services\FormErrorsService
        public: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaAutocompleteType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaDatePickerType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaDependentType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaIconType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaTreeSelectType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaCollectionContactType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaContactType:
        autowire: true

