services:
    Netliva\SymfonyFormBundle\Services\FormErrorsService:
        class: Netliva\SymfonyFormBundle\Services\FormErrorsService
        public: false

    netliva.form_errors:
        alias: Netliva\SymfonyFormBundle\Services\FormErrorsService
        public: true
