services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    Netliva\SymfonyFormBundle\Controller\AjaxAutocompleteController:
        autowire: true
        tags: ['controller.service_arguments']

    Netliva\SymfonyFormBundle\Controller\DependentController:
        autowire: true
        tags: ['controller.service_arguments']

    Netliva\SymfonyFormBundle\Controller\TreeSelectController:
        autowire: true
        tags: ['controller.service_arguments']

    Netliva\SymfonyFormBundle\Services\FormErrorsService:
        class: Netliva\SymfonyFormBundle\Services\FormErrorsService
        public: false

    netliva.form_errors:
        alias: Netliva\SymfonyFormBundle\Services\FormErrorsService
        public: true

    Netliva\SymfonyFormBundle\Services\CollectionContactExtension:
        class: Netliva\SymfonyFormBundle\Services\CollectionContactExtension
        public: false

    netliva.collection_contact_ext:
        alias: Netliva\SymfonyFormBundle\Services\CollectionContactExtension
        public: true

    Netliva\SymfonyFormBundle\Services\NetlivaCustomFieldsExtension:
        class: Netliva\SymfonyFormBundle\Services\NetlivaCustomFieldsExtension
        public: false

    netliva.custom_fields_ext:
        alias: Netliva\SymfonyFormBundle\Services\NetlivaCustomFieldsExtension
        public: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaCustomFieldsType:
        autowire: true
        tags: ['form.type']

    Netliva\SymfonyFormBundle\Form\Types\NetlivaSuggestiveTextType:
        autowire: true
        tags:
            - { name: 'form.type' }

    Netliva\SymfonyFormBundle\Form\Types\NetlivaAutocompleteType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaDatePickerType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaDependentType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaIconType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaTreeSelectType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaTrueFalseListType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaCollectionContactType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaContactType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaNumericSpinType:
        autowire: true

    Netliva\SymfonyFormBundle\Form\Types\NetlivaColorPickerType:
        autowire: true

